//restauratnsActionTypes
export const UPDATE_RESTAURANTS = 'UPDATE_RESTAURANTS';
export const UPDATE_COORDS = 'UPDATE_COORDS';
export const UPDATE_SELECTEDR = "UPDATE_SELECTEDR";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const UPDATE_CHOOSENFOODS = 'UPDATE_CHOOSENFOODS';



//uiActionTypes
export const UPDATE_LOADING = "UPDATE_LOADING";
export const UPDATE_SELECTEDC = "UPDATE_SELECTEDC";
export const UPDATE_TYPING = "UPDATE_TYPING";
export const UPDATE_LOADINGR = "UPDATE_LOADINGR";
export const UPDATE_SHOW_BACKDROP ="UPDATE_SHOW_BACKDROP";



//authActionTypes
export const UPDATE_USERA = "UPDATE_USERA";
